builds:
    - goos:
        - darwin
        - linux
        - windows
archives:
    -
      wrap_in_directory: true
      files:
          - CHANGELOG.md
          - LICENSE-APACHE
          - LICENSE-MIT
          - README.md
checksum:
  name_template: 'checksums.txt'
release:
  target_commitish: "{{ .FullCommit }}"
