version: 2
builds:
  - id: 'mm-geofeed-verifier'
    main: '.'
    goos:
      - darwin
      - linux
      - windows
    ldflags:
      - '-X main.version={{.Version}}'
archives:
    -
      wrap_in_directory: true
      files:
          - CHANGELOG.md
          - LICENSE-APACHE
          - LICENSE-MIT
          - README.md
checksum:
  name_template: 'checksums.txt'
release:
  target_commitish: "{{ .FullCommit }}"
